### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by T8RIN** [awxkee/avif-coder#13]
Sorry for asking here, do you know any maintained jpeg2000 decoders/encoders for Android?👀

**Comment by awxkee** [comment]
No, I don’t know any. I think it don’t exists due to a dead state of the format.

**Comment by T8RIN** [comment]
> No, I don’t know any. I think it don’t exists due to a dead state of the format.

Thanks :)

**Comment by T8RIN** [comment]
Also the which formats are most used today in real life?👀

**Comment by awxkee** [comment]
A lot of. In descending order PNG, JPG, SVG, GIF, Webp,hevc, AVIF, JPEG xl currently is at unknown stage due to google chrome ban and apple safari support, think it’ll survive. For some special cases also OpenExr, Raw formats, and sometimes people are using PDF instead of svg

**Comment by T8RIN** [comment]
Thanks !
