### ISSUE TITLE
Can the API version be adjusted to 21?

### ISSUE THREAD

**Issue by MrWuZhenQuan** [awxkee/avif-coder#20]

**Comment by awxkee** [comment]
As I remember aom could not be compiled against 21, it is possible to adjust by removing all libraries that could not be linked against 21 API. Btw I don’t remember exactly highly likely x265 or de265 also cannot be linked against 21

**Comment by awxkee** [comment]
Ofc you will lose part of functionally

**Comment by MrWuZhenQuan** [comment]
> As I remember aom could not be compiled against 21, it is possible to adjust by removing all libraries that could not be linked against 21 API. Btw I don’t remember exactly highly likely x265 or de265 also cannot be linked against 21

what is aom? 


> As I remember aom could not be compiled against 21, it is possible to adjust by removing all libraries that could not be linked against 21 API. Btw I don’t remember exactly highly likely x265 or de265 also cannot be linked against 21

Where can I obtain relevant info?  I tried to looking for answers at https://aomedia.googlesource.com/aom#microsoft-visual-studio-builds but found nothing about this

**Comment by awxkee** [comment]
I think you won't find the relevant info. I have build scripts in repository (or if you have experience with compiling C++ for NDK you may write your own) you have to modify target API version from 24 to 21 and try to compile libs and try to solve all the issues that y'll face

**Comment by MrWuZhenQuan** [comment]
thanks for the info
