### ISSUE TITLE
Compiling master encountered the following error

### ISSUE THREAD

**Issue by MrWuZhenQuan** [awxkee/avif-coder#23]
[CXX1429] error when building with cmake using *\avif-coder\app\src\main\cpp\CMakeLists.txt: C++ build system [configure] failed while executing:
    @echo off
    "*:\\Android\\SDK\\cmake\\3.22.1\\bin\\cmake.exe" ^
      "-HG:\\work\\avif-coder\\app\\src\\main\\cpp" ^
      "-DCMAKE_SYSTEM_NAME=Android" ^
      "-DCMAKE_EXPORT_COMPILE_COMMANDS=ON" ^
      "-DCMAKE_SYSTEM_VERSION=24" ^
      "-DANDROID_PLATFORM=android-24" ^
      "-DANDROID_ABI=arm64-v8a" ^
      "-DCMAKE_ANDROID_ARCH_ABI=arm64-v8a" ^
      "-DANDROID_NDK=*:\\Android\\SDK\\ndk\\25.1.8937393" ^
      "-DCMAKE_ANDROID_NDK=*:\\Android\\SDK\\ndk\\25.1.8937393" ^
      "-DCMAKE_TOOLCHAIN_FILE=*:\\Android\\SDK\\ndk\\25.1.8937393\\build\\cmake\\android.toolchain.cmake" ^
      "-DCMAKE_MAKE_PROGRAM=*:\\Android\\SDK\\cmake\\3.22.1\\bin\\ninja.exe" ^
      "-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=*:\\*avif-coder\\app\\build\\intermediates\\cxx\\Debug\\431y1p69\\obj\\arm64-v8a" ^
      "-DCMAKE_RUNTIME_OUTPUT_DIRECTORY=*:\\*avif-coder\\app\\build\\intermediates\\cxx\\Debug\\431y1p69\\obj\\arm64-v8a" ^
      "-DCMAKE_BUILD_TYPE=Debug" ^
      "-*:\\avif-coder\\app\\.cxx\\Debug\\431y1p69\\arm64-v8a" ^
      -GNinja

**Comment by awxkee** [comment]
There is only report that configuring failed, not the error itself. Please, check the log above and get the error.

**Comment by MrWuZhenQuan** [comment]
> There is only report that configuring failed, not the error itself. Please, check the log above and get the error.

I have solved it by clearing cache

**Comment by awxkee** [comment]
Yeah, this is the universal solution
