### ISSUE TITLE
Hello, this project supports png, jpg format image encoding into avif format?

### ISSUE THREAD

**Issue by xiaohei11111** [awxkee/avif-coder#28]
I see you said this project can be used for Android. Do you have a compiled apk android package for me to try it out? Because I'm not an Android student, I don't know how to compile this project into an Android package.

**Comment by awxkee** [comment]
No, it's not. To try this lib out at least you have to compile it. If you want to see some app that uses this lib for avif/hevc there is [ImageToolbox](https://github.com/T8RIN/ImageToolbox)

**Comment by xiaohei11111** [comment]
> No, it's not. To try this lib out at least you have to compile it. If you want to see some app that uses this lib for avif/hevc there is [ImageToolbox](https://github.com/T8RIN/ImageToolbox)不，不是。要试用此库，至少您必须编译它。如果您想查看一些将此库用于 avif/hevc 的应用程序，可以使用 [ImageToolbox](https://github.com/T8RIN/ImageToolbox)

I see. Thank you very much for your help. I'll try the toolbox.
