### ISSUE TITLE
Gradle import fail,need help.

### ISSUE THREAD

**Issue by fangzb** [awxkee/avif-coder#29]
Hi awxkee, When I import through Gradle：`implementation 'com.github.awxkee:avif-coder:2.0.6'` an error occurs:
`Null extracted folder for artifact: ResolvedArtifact(componentIdentifier=com.github.awxkee:avif-coder:2.0.6, variantName=null, artifactFile=/Users/eclipse/.gradle/caches/modules-2/files-2.1/com.github.awxkee/avif-coder/2.0.6/10d54edb6afc36d5dae19b8e07beca4d134f7756/avif-coder-2.0.6.aar, extractedFolder=null, dependencyType=ANDROID, isWrappedModule=false, buildMapping={__current_build__=/Users/eclipse/Develop/AndroidStudioProjects/wood-device}, mavenCoordinatesCache=com.android.build.gradle.internal.ide.dependencies.MavenCoordinatesCacheBuildService$Inject@204272f5)
`
do you have any suggestions？ thx

**Comment by awxkee** [comment]
I don’t know how to fix it

**Comment by fangzb** [comment]
> I don’t know how to fix it

thx bro. by the way I referenced your component in the Android Java project. Is there any difference between the introduction of Java and Kotlin?

**Comment by awxkee** [comment]
I never used this in Java project. However, there are should be no differences

**Comment by fangzb** [comment]
> 

ok, I'll try again. Anyway, thank you for this nice project!!!
