### ISSUE TITLE
Jxl support

### ISSUE THREAD

**Issue by T8RIN** [awxkee/avif-coder#4]
Thanks for creating such a great library, I don't know enough about NDK to write a jxl coder/encoder but if you can so, because you've already written avif coder, please create it, because there are literally NO alternatives unfortunately, thanks for attention, keep going!

**Comment by awxkee** [comment]
> Thanks for creating such a great library, I don't know enough about NDK to write a jxl coder/encoder but if you can so, because you've already written avif coder, please create it, because there are literally NO alternatives unfortunately, thanks for attention, keep going!

You may try simple implementation of JXL `https://github.com/awxkee/jxl-coder`. It won't work in all cases, like a alpha encoding and supports only RGBA 8bit images

**Comment by T8RIN** [comment]
Alpha is one of the jxl features :( did you plan to expand the opportunities of this library? It would be really helpful, and thanks for this implementation at least, but alpha is really needed...
