### ISSUE TITLE
Jitpack

### ISSUE THREAD

**Issue by T8RIN** [awxkee/avif-coder#7]
By some reason 
![image](https://github.com/awxkee/avif-coder/assets/52178347/6731bac7-2729-4bfb-bfdf-27676dd03bb8)
and i even can't get it from gradle :(

**Comment by T8RIN** [comment]
Maybe that's because i suddenly removed publishing plugin from gradle script...

**Comment by T8RIN** [comment]
1.0.23 still fails (

**Comment by awxkee** [comment]
> 1.0.23 still fails (

I think it will be at least ten more fails :)

**Comment by T8RIN** [comment]
24 built fine :)

**Comment by awxkee** [comment]
> 24 built fine :)

Try out I think it's done

**Comment by T8RIN** [comment]
> > 24 built fine :)
> 
> Try out I think it's done

will check now

**Comment by T8RIN** [comment]
Works, but i have this error 
![image](https://github.com/awxkee/avif-coder/assets/52178347/323dab37-37e3-4295-b7da-86809a832035)

**Comment by T8RIN** [comment]
That's the reason why i copied the source and added this to avif-coder build gradle
``` kotlin
 packaging {
        jniLibs {
            excludes.add("lib/*/liblog.so")
            useLegacyPackaging = false
            keepDebugSymbols.clear()
        }
    }

```

**Comment by awxkee** [comment]
I think it's your local problem

**Comment by awxkee** [comment]
Try clean gradle cache. Have a look on your paths, your project accidently imports two same named libraries from different paths

**Comment by awxkee** [comment]
Make `pickFirst` / `pickLatest` strategy or find out why you importing one library two times simultaneously

**Comment by T8RIN** [comment]
> Try clean gradle cache. Have a look on your paths, your project accidently imports two same named libraries from different paths

Nothing helps, only this packaging block, because gpuimage local module creates it too (

**Comment by T8RIN** [comment]
> Make `pickFirst` / `pickLatest` strategy or find out why you importing one library two times simultaneously

ll try now

**Comment by awxkee** [comment]
You're definitely mixing up something. GPU image produces `libyuv-decoder.so` library

**Comment by awxkee** [comment]
If you has cloned my avif and have a sub project then you imports somewhere remote `avif-coder` and local `avif-coder` at the same time: They producing the same files and it fails

**Comment by T8RIN** [comment]
> If you has cloned my avif and have a sub project then you imports somewhere remote `avif-coder` and local `avif-coder` at the same time: They producing the same files and it fails

Let me explain, i have different product flavors, on is FOSS and there i need your remote dependency, and i has market flavor where i use modified cloned module

**Comment by T8RIN** [comment]
> Make `pickFirst` / `pickLatest` strategy or find out why you importing one library two times simultaneously

this one helped!
![image](https://github.com/awxkee/avif-coder/assets/52178347/30521d9d-e4f4-4094-9386-db1db7b171af)
thanks :)

**Comment by awxkee** [comment]
Fine, why don't do 'fossImplementation 'remote avif'` 'debugImpleementation 'local-avif' 'releaseImplementation` ?

**Comment by awxkee** [comment]
> > Make `pickFirst` / `pickLatest` strategy or find out why you importing one library two times simultaneously
> 
> this one helped! ![image](https://user-images.githubusercontent.com/52178347/265105162-30521d9d-e4f4-4094-9386-db1db7b171af.png) thanks :)

Better do the right imports because it' quite gold hammer strategy for your case

**Comment by T8RIN** [comment]
> Fine, why don't do 'fossImplementation 'remote avif'` 'debugImpleementation 'local-avif' 'releaseImplementation` ?

![image](https://github.com/awxkee/avif-coder/assets/52178347/f5c8bfbd-f5ec-499d-9242-069b26d557ad)

using that way

**Comment by awxkee** [comment]
Okay. Then double check that you don't have cycling deps because this one should works well if you didn't do the cycle

**Comment by awxkee** [comment]
Maybe one more project exporting same project?

**Comment by T8RIN** [comment]
Definitely no, because they are not rely on each other, but maybe i didn't get something :(

**Comment by awxkee** [comment]
> Definitely no, because they are not rely on each other, but maybe i didn't get something :(
If you cloned the project it this possible that avif-coil depends on avif-coder?

**Comment by T8RIN** [comment]
Also, can i request only one addition to heif coder please?

![image](https://github.com/awxkee/avif-coder/assets/52178347/9a73a48d-5a20-48d7-b95d-18aea7194cb6)

Could you add this dummy check? Because my app uses api 21 and on older than 24 i close avif using on client side, so all is fine, but if this check not here app crashes  :(

**Comment by T8RIN** [comment]
> If you cloned the project it this possible that avif-coil depends on avif-coder?

Yes, it is, i will exlude now

**Comment by awxkee** [comment]
> Also, can i request only one addition to heif coder please?
> 
> ![image](https://user-images.githubusercontent.com/52178347/265106166-9a73a48d-5a20-48d7-b95d-18aea7194cb6.png)
> 
> Could you add this dummy check? Because my app uses api 21 and on older than 24 i close avif using on client side, so all is fine, but if this check not here app crashes :(

I may give you the general recommendation never do this way :)

But if it is necessary your app should handle as I remember not an ancestor of `Exception` but an ancestor of `Error`.
Generally speaking you should be able to intercept this error you will catch the right ancestor of error.

**Comment by T8RIN** [comment]
> > Also, can i request only one addition to heif coder please?
> > ![image](https://user-images.githubusercontent.com/52178347/265106166-9a73a48d-5a20-48d7-b95d-18aea7194cb6.png)
> > Could you add this dummy check? Because my app uses api 21 and on older than 24 i close avif using on client side, so all is fine, but if this check not here app crashes :(
> 
> I may give you the general recommendation never do this way :)
> 
> But if it is necessary your app should handle as I remember not an ancestor of `Exception` but an ancestor of `Error`. Generally speaking you should be able to intercept this error you will catch the right ancestor of error.

But if i use your remote dependency i can't handle system crash if user has lower api, because init block just happens

**Comment by awxkee** [comment]
Ok. But actually I don't remember why I chose 24 as a minimum give me some time to check maybe I may just compile for 21 all the libs

**Comment by T8RIN** [comment]
> Ok. But actually I don't remember why I chose 24 as a minimum give me some time to check maybe I may just compile for 21 all the libs

i'll wait for the updares then :)

**Comment by awxkee** [comment]
> > Ok. But actually I don't remember why I chose 24 as a minimum give me some time to check maybe I may just compile for 21 all the libs
> 
> i'll wait for the updares then :)

No, no way. Only if remove heic with heif support then possible.
But check is already added. It should be in 1.0.24 release. Is it not enough?

**Comment by T8RIN** [comment]
> > > Also, can i request only one addition to heif coder please?
> > > ![image](https://user-images.githubusercontent.com/52178347/265106166-9a73a48d-5a20-48d7-b95d-18aea7194cb6.png)
> > > Could you add this dummy check? Because my app uses api 21 and on older than 24 i close avif using on client side, so all is fine, but if this check not here app crashes :(
> > 
> > I may give you the general recommendation never do this way :)
> > 
> > But if it is necessary your app should handle as I remember not an ancestor of `Exception` but an ancestor of `Error`. Generally speaking you should be able to intercept this error you will catch the right ancestor of error.
> 
> But if i use your remote dependency i can't handle system crash if user has lower api, because init block just happens

You mean this one?

**Comment by awxkee** [comment]
> > > > Also, can i request only one addition to heif coder please?
> > > > ![image](https://user-images.githubusercontent.com/52178347/265106166-9a73a48d-5a20-48d7-b95d-18aea7194cb6.png)
> > > > Could you add this dummy check? Because my app uses api 21 and on older than 24 i close avif using on client side, so all is fine, but if this check not here app crashes :(
> > > 
> > > 
> > > I may give you the general recommendation never do this way :)
> > > But if it is necessary your app should handle as I remember not an ancestor of `Exception` but an ancestor of `Error`. Generally speaking you should be able to intercept this error you will catch the right ancestor of error.
> > 
> > 
> > But if i use your remote dependency i can't handle system crash if user has lower api, because init block just happens
> 
> You mean this one?

Yes, that one
<img width="785" alt="image" src="https://github.com/awxkee/avif-coder/assets/17083179/90f61d0a-8159-44e6-bd45-f4af8c0ba9bc">

**Comment by T8RIN** [comment]
> > > > > Also, can i request only one addition to heif coder please?
> > > > > ![image](https://user-images.githubusercontent.com/52178347/265106166-9a73a48d-5a20-48d7-b95d-18aea7194cb6.png)
> > > > > Could you add this dummy check? Because my app uses api 21 and on older than 24 i close avif using on client side, so all is fine, but if this check not here app crashes :(
> > > > 
> > > > 
> > > > I may give you the general recommendation never do this way :)
> > > > But if it is necessary your app should handle as I remember not an ancestor of `Exception` but an ancestor of `Error`. Generally speaking you should be able to intercept this error you will catch the right ancestor of error.
> > > 
> > > 
> > > But if i use your remote dependency i can't handle system crash if user has lower api, because init block just happens
> > 
> > You mean this one?
> 
> Yes, that one
> <img width="785" alt="image" src="https://github.com/awxkee/avif-coder/assets/17083179/90f61d0a-8159-44e6-bd45-f4af8c0ba9bc">
> 

Yup, it is enough, thanks!

**Comment by T8RIN** [comment]
I have another problem, again...

when trying to exclude transitive copy of avif-coder i get this error
``` kotlin
implementation(project(":avif-coder-coil")) {
        isTransitive = false
    }
```
``` error
Cannot change dependencies of dependency configuration ':avif-coder-coil:api' after it has been included in dependency resolution.
```

but when i try to not exclude i get duplicate classes packaged into jar (

**Comment by awxkee** [comment]
It won't work this way. You have to do related Flavors as in main project for you subproject too. But this is quite annoying and in fact I recommend you just delete `avif-coder-coil` and copy this one file from it to the root.

**Comment by T8RIN** [comment]
> It won't work this way. You have to do related Flavors as in main project for you subproject too. But this is quite annoying and in fact I recommend you just delete `avif-coder-coil` and copy this one file from it to the root.

Okay, and also there is problem with coil remote dependency: 
Could not GET 'https://jitpack.io/com/github/awxkee/avif-coder-coil/1.0.24/avif-coder-coil-1.0.24.pom'. Received status code 401 from server: Unauthorized

**Comment by awxkee** [comment]
Surpringly but jitpack doesn't work this way. It squashes all projects that provides publishing into one. After you added `avif-coder` all classes from coil framework should be visible too

**Comment by T8RIN** [comment]
> Surpringly but jitpack doesn't work this way. It squashes all projects that provides publishing into one. After you added `avif-coder` all classes from coil framework should be visible too

:)))))))))) gradle gonna kill me soon

**Comment by T8RIN** [comment]
> > It won't work this way. You have to do related Flavors as in main project for you subproject too. But this is quite annoying and in fact I recommend you just delete `avif-coder-coil` and copy this one file from it to the root.
> 
> Okay, and also there is problem with coil remote dependency: Could not GET 'https://jitpack.io/com/github/awxkee/avif-coder-coil/1.0.24/avif-coder-coil-1.0.24.pom'. Received status code 401 from server: Unauthorized

and what is it also?

**Comment by awxkee** [comment]
> > > It won't work this way. You have to do related Flavors as in main project for you subproject too. But this is quite annoying and in fact I recommend you just delete `avif-coder-coil` and copy this one file from it to the root.
> > 
> > 
> > Okay, and also there is problem with coil remote dependency: Could not GET 'https://jitpack.io/com/github/awxkee/avif-coder-coil/1.0.24/avif-coder-coil-1.0.24.pom'. Received status code 401 from server: Unauthorized
> 
> and what is it also?

Jitpack provides only one source of truth - the main packaga name that correlates to github proj name so for `avif-coder` it is `implementation 'com.github.awxkee:avif-coder:Tag` where all projects from `avif-coder` squashed into it.
And other endpoint means unexisting or "you have no rights" for privacy reasons.

For existing this endpoint I must created project name `avif-coder-coil` and do all the stuff there...

**Comment by T8RIN** [comment]
ohhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh

**Comment by T8RIN** [comment]
Got it, i removed coil dependency for foss
![image](https://github.com/awxkee/avif-coder/assets/52178347/42e9fddc-ae7f-4cef-977e-5dcd0812e47a)
now it builds :)

**Comment by awxkee** [comment]
Well done

**Comment by T8RIN** [comment]
Thanks for your support and answers!!
