### ISSUE TITLE
The new version doesn't work

### ISSUE THREAD

**Issue by T8RIN** [awxkee/avif-coder#9]
I've just tried a new library version and it is not displaying images, and also not saving them, something went wrong with encode and decode functions i think, also no errors during these processes are thrown... F.e. version 1.0.24 work as expected

**Comment by awxkee** [comment]
> I've just tried a new library version and it is not displaying images, and also not saving them, something went wrong with encode and decode functions i think, also no errors during these processes are thrown... F.e. version 1.0.24 work as expected
There should be definitely an exception somewhere, may you check for it? I done tons of math for hdr some glitches may happen

**Comment by awxkee** [comment]
> 

Also if that possible I would like to ask you a few images that you trying to display

**Comment by T8RIN** [comment]
> > I've just tried a new library version and it is not displaying images, and also not saving them, something went wrong with encode and decode functions i think, also no errors during these processes are thrown... F.e. version 1.0.24 work as expected
> 
> There should be definitely an exception somewhere, may you check for it? I done tons of math for hdr some glitches may happen 

Maybe yes, but i have exceptions handlers everywhere, and nothing just happens

**Comment by T8RIN** [comment]
> > 
> 
> Also if that possible I would like to ask you a few images that you trying to display

This happens with every image , i.e. coil loader now just breaks everything, i can't even display jpg, because heif coder fails, i will check it's logs now, and send the app compiled with the new version

**Comment by awxkee** [comment]
> > > I've just tried a new library version and it is not displaying images, and also not saving them, something went wrong with encode and decode functions i think, also no errors during these processes are thrown... F.e. version 1.0.24 work as expected
> > 
> > 
> > There should be definitely an exception somewhere, may you check for it? I done tons of math for hdr some glitches may happen
> 
> Maybe yes, but i have exceptions handlers everywhere, and nothing just happens

If you have an exceptions handle everywhere it definitely an error 'somewhere handled'

**Comment by T8RIN** [comment]
> > > > 
> > > 
> > > 
> > > Also if that possible I would like to ask you a few images that you trying to display
> > 
> > This happens with every image , i.e. coil loader now just breaks everything, i can't even display jpg, because heif coder fails, i will check it's logs now, and send the app compiled with the new version
> 
> Are you trying '1.1.4' version?
> 

Yes

**Comment by T8RIN** [comment]
> > > > I've just tried a new library version and it is not displaying images, and also not saving them, something went wrong with encode and decode functions i think, also no errors during these processes are thrown... F.e. version 1.0.24 work as expected
> > > 
> > > 
> > > There should be definitely an exception somewhere, may you check for it? I done tons of math for hdr some glitches may happen
> > 
> > Maybe yes, but i have exceptions handlers everywhere, and nothing just happens
> 
> If you have an exceptions handle everywhere it definitely an error 'somewhere handled'

I mean they handled and shown to user, but with coil factories this doesn't work, and errors just shown in error block of coil loader, so i'll check what happens internally

**Comment by awxkee** [comment]
> > > 
> > 
> > 
> > I found it. It just coil decoder related issue. I'm on it
> 
> Oh, okay, waiting!

I made the fix

**Comment by T8RIN** [comment]
Could you also fix jxl Loosy to Lossy and Loseless to Lossless ? (there is typos i think)

**Comment by T8RIN** [comment]
> > > > 
> > > 
> > > 
> > > I found it. It just coil decoder related issue. I'm on it
> > 
> > 
> > Oh, okay, waiting!
> 
> I made the fix

will check now

**Comment by awxkee** [comment]
> Could you also fix jxl Loosy to Lossy and Loseless to Lossless ? (there is typos i think)

Done

**Comment by T8RIN** [comment]
By some reason now your coil factory cannot determine if this is an heif file... and brokes everything after

**Comment by awxkee** [comment]
> > > > > 
> > > > 
> > > > 
> > > > I found it. It just coil decoder related issue. I'm on it
> > > 
> > > 
> > > Oh, okay, waiting!
> > 
> > 
> > I made the fix
> 
> ![image](https://user-images.githubusercontent.com/52178347/265723438-f0902eef-ac8f-4024-9251-12a1e03ad14a.png)
> 
> not working :(

It is not mine. My coil plugin do not using BitmapFactory

**Comment by awxkee** [comment]
> I know, check the latest PR from me

It is definitely not right to check that `ftyp`. Tons of formats using `ftyp` starting from MP-4 finishing by avif

**Comment by T8RIN** [comment]
> > I know, check the latest PR from me
> 
> It is definitely not right to check only `ftyp`. Tons of formats using `ftyp` starting from MP-4 finishing by avif

Then you could implement personal checking, but using buffered source, without "eating" bytearray

**Comment by awxkee** [comment]
> That how i used it in jxl-coder based coil

Yep, I know. But HEIC, HEIF and AVIF are different from JXL you can't check that this way

**Comment by awxkee** [comment]
Ok. I think I'll do same. But it's unclear why BufferedSource in coil is just `one-shot`

**Comment by T8RIN** [comment]
> > That how i used it in jxl-coder based coil
> 
> Yep, I know. But HEIC, HEIF and AVIF are different from JXL you can't check that this way
> 

Then how are you checking if the bytearray contains heif data?

**Comment by awxkee** [comment]
> > Ok. I think I'll do same. But it's unclear why BufferedSource in coil is just `one-shot`
> 
> Maybe in performance purposes?

BufferedSource means it's buffered... If you `buffering` some it means it should be always available until deleted.

I'm making validation via libheif, it is the most exact way to be sured that image is valid.
Another ways will lead to false-positive results, but if coil work this way I'll do another

**Comment by T8RIN** [comment]
> > > Ok. I think I'll do same. But it's unclear why BufferedSource in coil is just `one-shot`
> > 
> > Maybe in performance purposes?
> 
> BufferedSource means it's buffered... If you `buffering` some it means it should be always available until deleted.
> 
> I'm making validation via libheif, it is the most exact way to be sured that image is valid.
> Another ways will lead to false-positive results, but if coil work this way I'll do another

Okay, got it :)

**Comment by awxkee** [comment]
> 

Try '1.1.7' version
